config/routes.rb
Rails.application.routes.draw do
  
  resources :task_lists do
    resources :tasks
  end

  resources :tags

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "task_lists#index"
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  date         :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  task_list_id :integer          not null
#  is_done      :boolean          default(FALSE)
#  repeat       :integer          default(0)
#
class Task < ApplicationRecord
  belongs_to :task_list
  has_many :tags_task
  has_many :tags, through: :tags_task # Using join model TagsTask

  validates :title, presence: true
  validates :description, presence: true
  validates :task_list, presence: true

  # Checks if the current task is overdue
  def is_overdue
    (date && Time.zone.at(date).past?) || false
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  require "validations/task_transaction"

  before_action :set_task, only: %i[ edit update destroy ]
  before_action :get_tag_list, only: %i[ edit ]

  def edit
    @task_list = @task.task_list
  end

  # POST /tasks or /tasks.json
  def create
    task_list = TaskList.find(params[:task_list_id])

    TaskTransaction.new.with_step_args(persist: [task_list, Task.new]).call(params) do |on|
      on.success { |t| redirect_to task_list_path(task_list), notice: "Task was created successfully." and return }
      on.failure(:validate) { |v| redirect_to task_list_path(task_list), notice: v and return }
      on.failure { |e| redirect_to task_list_path(task_list), notice: e and return }
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    task_list = @task.task_list

    TaskTransaction.new.with_step_args(persist: [task_list, @task]).call(params) do |on|
      on.success { |t| redirect_to task_list_path(task_list), notice: "Task was successfully updated." and return }
      on.failure(:validate) { |v| redirect_to edit_task_list_task_path(task_list_id: task_list.id, id: @task.id), notice: v and return }
      on.failure { |e| redirect_to edit_task_list_task_path(task_list_id: task_list.id, id: @task.id), notice: e and return }
    end

  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task_list = @task.task_list
    begin
      @task.destroy!
      redirect_to task_list_path(@task_list), notice: "Task deleted" and return
    rescue
      redirect_to task_list_path(@task_list), notice: "Error: Unable to delete task" and return
    end
  end

  private
    def get_tag_list
      @tags = Tag.all
    end

    def set_task
      @task = Task.find(params[:id])
    end


    # Only allow a list of trusted parameters through.\
    # These params match the ones passed from the view
    # NOTE: tag_ids as array
    # NOTE: Responsibility passed to TaskTransaction
    # def task_params
    #   params.require(:task).permit(:title, :description, :date, :is_done, :repeat, :tag_ids=>[])
    # end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with model: [ @task_list, @task ] do |form| %>

  <% if @task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% @task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div>
    <%= form.label :date, class: "form-label" %>
    <%= form.datetime_field :date, class: "form-control" %>
  </div>

  <div class="row mt-3">
    <div class="col-auto">
      <div class="form-check">
        <%= form.label 'Repeat', class: "form-check-label" %>
        <%= form.check_box :set_repeat, checked: @task.repeat.positive?, class: "form-check-input" %>
      </div>
    </div>
    <div class="col-auto">
      <%= form.label 'Every (Days)', class: "form-check-label" %>
    </div>
    <div class="col-auto">
      <%= form.number_field :repeat, :class => 'form-control', :type => 'number' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :tags, class: "form-label" %>
    <%= form.collection_select :tag_ids, @tags.order(:name), :id, :name, {}, { class: "form-control", multiple: true } %>
  </div>

  <div class="form-check">
    <%= form.label :is_done, class: "form-check-label" %>
    <%= form.check_box :is_done, class: "form-check-input" %>
  </div>

  <div>
    <%= form.submit :Submit, class: "btn btn-primary mt-4" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="card h-100 <%= 'border-danger' if task.is_overdue %>">

  <div class="card-header">
    <div class="row">
      <div class="col">
        <h5 class="h5"><%= task.title %></h5>
      </div>
      <% if defined?(tags_count) %>
      <div class="col-auto">
        <span class="badge rounded-pill bg-info text-dark"><%= tags_count %></span>
      </div>
      <% end %>
    </div>
  </div>

  <div class="card-body">

    <% if task.tags.length.positive? %>
      <p class="card-text">
        <small class="text-muted">
          <% task.tags.each do | tg | %>
            <%= tg.name %> |
          <% end %>
        </small>
      </p>
    <% end %>

    <p class="card-text"><small class="<%= task.is_overdue ? 'text-danger' : 'text-muted' %>"><%= task.date %></small></p>

    <% if task.repeat.positive? %>
      <p class="card-text"><small class="text-muted">Repeating every <%= task.repeat %> days</small></p>
    <% end %>

    <p class="card-text"><%= task.description %></p>
  </div>

  <div class="card-footer bg-transparent">
    <div class="row">
      <div class="col-auto ms-auto">
        <%= button_to "Edit this task", edit_task_list_task_path(task_list_id: task.task_list.id, id: task.id), method: :get, class: 'btn btn-sm btn-outline-success' %>  
      </div>
      <div class="col-auto">
        <%= button_to "Destroy this task", task_list_task_path(task_list_id: task.task_list.id, id: task.id),
                                      method: :delete,
                                      data: { confirm: "Are you sure?" },
                                      class: 'btn btn-sm btn-outline-danger' %>
      </div>
    </div>
  </div>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<p style="color: green"><%= notice %></p>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to task list", @task.task_list %>
</div>