config/routes.rb
Rails.application.routes.draw do
  
  resources :task_lists do
    resources :tasks
  end

  resources :tags

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "task_lists#index"
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tag < ApplicationRecord
  has_many :tags_task
  has_many :tasks, through: :tags_task # Using join model TagsTask

  validates :name, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    begin
      @tag.save!
      redirect_to tags_path, notice: "Tag was successfully created." and return

    rescue
      render :new, status: :unprocessable_entity and return
    end

  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    begin
      @tag.update!(tag_params)
      redirect_to tags_path, notice: "Tag was successfully updated." and return

    rescue
      render :edit, status: :unprocessable_entity and return
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    begin
      @tag.destroy!
      redirect_to tags_url, notice: "Tag was successfully destroyed." and return
    rescue
      redirect_to tags_url, notice: "Error: Unable to delete tag" and return
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Name:</strong>
    <%= tag.name %>
  </p>

</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tags</h1>

<div id="tags">
  <ul class="list-group">
    
    <% @tags.each do |tag| %>
      <li class="list-group-item">
        <div class="row">
          <div class="col">
            <%= tag.name %>
          </div>
          <div class="col-auto">
            <%= button_to "Edit this tag", edit_tag_path(tag), method: :get, class: "btn btn-sm btn-link" %>
          </div>
          <div class="col-auto">
            <%= button_to "Destroy this tag", tag, method: :delete, class: "btn btn-sm btn-link" %>
          </div>
        </div>
      </li>
    <% end %>

  </ul>

</div>

<%= link_to "New tag", new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Back to tags", tags_path %>
</div>