config/routes.rb
Rails.application.routes.draw do
  
  resources :task_lists do
    resources :tasks
  end

  resources :tags

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "task_lists#index"
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  date         :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  task_list_id :integer          not null
#  is_done      :boolean          default(FALSE)
#  repeat       :integer          default(0)
#
class Task < ApplicationRecord
  belongs_to :task_list
  has_many :tags_task
  has_many :tags, through: :tags_task # Using join model TagsTask

  validates :title, presence: true
  validates :description, presence: true
  validates :task_list, presence: true

  # Checks if the current task is overdue
  def is_overdue
    (date && Time.zone.at(date).past?) || false
  end
end

app/models/task_list.rb
# == Schema Information
#
# Table name: task_lists
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class TaskList < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :title, presence: true, length: { minimum: 1 }
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  include TaskListsHelper

  before_action :set_task_list, only: %i[ show edit update destroy ]
  before_action :get_tag_list, only: %i[ show ]

  # GET /task_lists or /task_lists.json
  def index
    @task_lists = TaskList.all
  end

  # GET /task_lists/1 or /task_lists/1.json
  def show
    # checks if params[:task_list] exists. Then checks if params[:task_list][:tag_ids]
    # and rejects empty values. If these conditions are not present, sets "tags" to
    # an empty array
    tags = (params[:task_list] && params[:task_list][:tag_ids]&.reject(&:empty?)) || []
    chosen_tags = Tag.where(id: tags)

    @tasks = get_filtered_tasks(chosen_tags, @task_list).paginate(page: params[:page], per_page: 6)

    @task = Task.new
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists or /task_lists.json
  def create
    begin
      @task_list = TaskList.create!(task_list_params)
      redirect_to task_list_url(@task_list), notice: "Task list was successfully created." and return
    rescue
      render :new, status: :unprocessable_entity and return
    end
  end

  # PATCH/PUT /task_lists/1 or /task_lists/1.json
  def update
    begin
      @task_list.update!(task_list_params)
      redirect_to task_list_url(@task_list), notice: "Task list was successfully updated." and return
    rescue
      render :edit, status: :unprocessable_entity and return
    end
  end

  # DELETE /task_lists/1 or /task_lists/1.json
  def destroy
    begin
      @task_list.destroy!
      redirect_to task_lists_url, notice: "Task list was successfully destroyed." and return
    rescue
      redirect_to task_lists_url, notice: "Unable to destroy task list" and return
    end
  end

  private
    def get_tag_list
      @tags = Tag.all
    end

    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_list_params
      params.require(:task_list).permit(:title)
    end
end

app/helpers/task_lists_helper.rb
module TaskListsHelper

  # Returns a list of tasks filtered by tags and task list
  def get_filtered_tasks(tags, task_list)

    if tags.length.positive? # Checking for positive values
      tasks = []

      for tg in tags do
        # |= adds an element to the array unless it is akready present
        # The element must be wrapped in an array, that's why it works as an "add all"
        # by using a collection (tg.tasks)
        tasks |= tg.tasks.where(task_list: task_list) # relative to task list
      end

    else
      tasks = task_list.tasks
    end

    tasks
  end

end

app/views/task_lists/_form.html.erb
<%= form_with model: task_list do |form| %>
  <% if task_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
        <% task_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
    <%= form.submit :Submit, class: "btn btn-primary mt-4" %>
  </div>
<% end %>

app/views/task_lists/_task_list.html.erb
<div id="<%= dom_id task_list %>">
  <p>
    <strong>title:</strong>
    <%= task_list.title %>
  </p>

</div>

app/views/task_lists/edit.html.erb
<h1>Editing task list</h1>

<%= render "form", task_list: @task_list %>

<br>

<div>
  <%= link_to "Show this task list", @task_list %> |
  <%= link_to "Back to task lists", task_lists_path %>
</div>

app/views/task_lists/index.html.erb
<div class="row">

  <div class="col-12">
    <h1>Task lists</h1>
    <p style="color: green"><%= notice %></p>
  </div>

  <div class="col-12">
    <%= button_to "New task list", new_task_list_path, method: :get, class: 'btn btn-sm btn-outline-primary' %>
  </div>

  <div class="col-12 mt-3">
  
    <ul id="task_lists" class="list-group">

      <% @task_lists.each do |task_list| %>
        <li class="list-group-item">
          <h3 class="h3"><%= task_list.title %></h2>
          <p><%= link_to "Show this task list", task_list %></p>
        </li>
      <% end %>

    </ul>
  
  </div>

</div>

app/views/task_lists/new.html.erb
<h1>New task list</h1>

<%= render "form", task_list: @task_list %>

<br>

<div>
  <%= link_to "Back to task lists", task_lists_path %>
</div>

app/views/task_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col-12 offset-0
              col-md-8 offset-md-2
              col-lg-6 offset-lg-3">
    <h2 class="h2">Add a task:</h2>
    <%= render 'tasks/form' %>
  </div>

  <div class="col-12 mt-4">
    <h1 class="h1 mt-4 mb-3"><%= @task_list.title %></h1>
      <% if @task_list.tasks.empty? %>
        <p>This list has no tasks</p>

      <% else %>
        <div class="row">
          <div class="col-12">
            <%= form_with model: @task_list, method: :get do |form| %>
              <div class="form-group">
                <%= form.label "Filter by tags", class: "form-label" %>
                <%= form.collection_select :tag_ids, @tags.order(:name), :id, :name, {}, { class: "form-control", multiple: true, size: 3 } %>
              </div>
              <div>
                <%= form.submit "Filter", class: "btn btn-primary mt-4" %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="row">

          <div class="col-12">
            <%= will_paginate @tasks %>
          </div>
          
          <% @tasks.each do | t | %>
            <div class="col-12 col-md-6 col-lg-4 mt-3">
              <%= render "tasks/task", task: t, tags_count: t.tags.count %>  
            </div>
          <% end %>

          <div class="col-12">
            <%= will_paginate @tasks %>
          </div>

        </div>

    <% end %>
  </div>

  <div class="col-12 mt-4">
    <h4 class="h4">Options</h4>
    <div class="row">
      <div class="col-auto pr-0">
        <%= button_to "Back to task lists", task_lists_path, method: :get, class: 'btn btn-sm btn-outline-primary' %>
      </div>
      <div class="col-auto px-0">
        <%= button_to "Edit this task list", edit_task_list_path(@task_list), method: :get, class: 'btn btn-sm btn-outline-success' %>
      </div>
      <div class="col-auto pl-0">
        <%= button_to "Destroy this task list", @task_list, method: :delete, class: 'btn btn-sm btn-outline-danger' %>
      </div>
    </div>
  </div>
</div>