config/routes.rb
Rails.application.routes.draw do
  
  resources :task_lists do
    resources :tasks
  end

  resources :tags

  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "task_lists#index"
end

app/views/layouts/_footer.html.erb
<div class="card text-center mt-5">
  <div class="card-header">
    Footer
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">RR Tasks</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Task Lists", root_path, class: 'nav-link' %></a>
        </li>
        <li class="nav-item">
          <%= link_to "New List", new_task_list_path, class: 'nav-link' %></a>
        </li>
        <li class="nav-item">
          <%= link_to "Manage Tags", tags_path, class: 'nav-link' %></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RR Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container" style="min-height: 80vh">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>